# Generated by Django 5.0.7 on 2024-07-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["done"]},
        ),
    ]
